### PR TITLE
Document how to run tests inside containers

### PR DESCRIPTION
**Pull request by mruffalo**

### CODE REVIEW

**Comment by mruffalo** [comment]
`flake8` was missing from the development Python container due to an oversight of mine. Sorry about that -- it's included in the one I built and pushed yesterday. `docker-compose pull` will download the newer one. (See https://github.com/hubmapconsortium/hubmap-data-portal/pull/80/commits/c23a90a93666befdef8374ae6d5b42de258bb1be.)

I do think it's worth standardizing things to be run in the container and adding some scripting to do so; this removes any environmental differences between machines and doesn't require anything to be installed on the host except for Docker.

**Comment by mccalluc** [comment]
Cool: Let me pull and I'll try to write a script for this. (Generally, If something is just a sequence of steps, I would like to script it: Easier for the end user, and more likely that we'll keep it up to date... but sometimes explaining the process is as important as just running it, and that's a good case for putting it in the readme or other docs.)

**Comment by mccalluc** [comment]
@mruffalo : See #92: I would prefer to do this with a script, but I won't block if you believe that explaining the process in a doc is better. In either case, I think it's also worth noting that installing dev tools on production environments is not the usual practice... If you would like to go ahead and merge either this or #92, perhaps file a tech-debt issue as a reminder of this quirk.  In your court.

**Comment by mruffalo** [comment]
I'd prefer doing this with a script also, so this PR can be dropped in favor of "run this script."

**Pull request closed without merging**
