### PR TITLE
eslint --init

### PR DESCRIPTION
**Pull request by mccalluc**
eslint starts to become more useful when you tell it about your codebase:
```
$ eslint --init
? How would you like to use ESLint? To check syntax, find problems, and enforce code style
? What type of modules does your project use? JavaScript modules (import/export)
? Which framework does your project use? React
? Where does your code run? (Press <space> to select, <a> to toggle all, <i> to invert selection)Browser
? How would you like to define a style for your project? Use a popular style guide
? Which style guide do you want to follow? Airbnb (https://github.com/airbnb/javascript)
? What format do you want your config file to be in? YAML
```
... and then I've ignored all the errors which were reported, to keep this PR small. They will be fixed in successive PRs

The only part that's subjective is the choice of airbnb style rules. It's what I've used on Vitessce, with a small number of overrides, and it feels comfortable. We can change it down the road, if needed.

This passes locally for me... We'll see how it works on Travis. Replaces #71

### CODE REVIEW

**Comment by mccalluc** [comment]
1: Does `cd hubmap/frontend; $(npm bin)/eslint .` work for you? The command is simple enough: if you can't run it, then there's a problem with the setup we should fix -- just adding an alias in package.json wouldn't do anything.

1b: But you shouldn't need to run it on the command line often: Your IDE should be able to read the eslint config and highlight any problems.

2+3: My preference would be to merge this now, or soon, and then make another PR with automatic fixes for whitespace, merge that, and then work through the ones that will require more thought: We'll remove files from the ignore list, and remove individual ignores.

**Comment by mruffalo** [comment]
Does #90 help with this?

**Comment by mruffalo** [comment]
Looks good to me though.

**Comment by sushma-ananda** [comment]
@mccalluc 
1) yes that works for me, but why arent we looking at adding a command in package.json?
2) While I was working on configuring eslint for webpack-config (on my private repo that you and Matt have access to), apparently having **_error  Parsing error: Unexpected token =_** is not an error, so it requires "parser": "babel-eslint". Why aren't we using this parser ?

**Comment by mccalluc** [comment]
1. Sure, I can add an alias: Just wanted to be sure there wasn't another problem.
2. I just wasn't sure what the fix was right then: Great - whatever works.

Thanks!

**Pull request merged**
