### PR TITLE
Install SCSS

### PR DESCRIPTION
**Pull request by mccalluc**
I think that scss will be better than raw css. Installing the dependencies seems to depend on the host system: I first got this...
<details>

```
react_app_1      | Failed to compile.
react_app_1      | 
react_app_1      | ./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/App.scss)
react_app_1      | Error: Missing binding /opt/hubmap-data-portal/hubmap/frontend/node_modules/node-sass/vendor/linux-x64-72/binding.node
react_app_1      | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
react_app_1      | 
react_app_1      | Found bindings for the following environments:
react_app_1      |   - OS X 64-bit with Node.js 9.x
react_app_1      | 
react_app_1      | This usually happens because your environment has changed since running `npm install`.
react_app_1      | Run `npm rebuild node-sass` to download the binding for your current environment.
```

</details>

but I think it works now.

(Not actually SCSS-ifying anything here: want to be sure we're on board with this before investing more time.)

### CODE REVIEW

**Comment by mccalluc** [comment]
Hmm: flake8 fails; Nothing in this PR should have changed that. Did something bad get checked into develop? Investigating...

**Comment by mruffalo** [comment]
I totally agree about using some extension to CSS; Sushma and I had discussed possibly using LESS. I don't have a preference about SASS vs. SCSS vs. LESS though.

**Comment by mccalluc** [comment]
This is trivial, so I'm going to close it, file an issue to get consensus on which language to use, and go from there.

**Comment by mccalluc** [comment]
Filed #109 to get consensus on the way forward.

**Pull request merged**
