### PR TITLE
Make readme more concise

### PR DESCRIPTION
**Pull request by mccalluc**
Several small edits to bring the readme into focus on just the information that really matters.

### CODE REVIEW

**Review by jswelling — APPROVED** [review]

**Review by jswelling — APPROVED** [review]
Reference the nginx docs from the top-level readme?

**Review by jswelling — APPROVED** [review]
Did the ToDo list move somewhere canonical?

**Comment by mccalluc** [comment]
> Did the ToDo list move somewhere canonical?

I just filed #169. Thanks!

**Comment by mccalluc** [comment]
> Reference the nginx docs from the top-level readme?

Done.

**Pull request merged**
